package test.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _BaseEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BaseEntity extends CayenneDataObject {

    public static final String REF_PROPERTY = "ref";

    public static final String ID_PK_COLUMN = "ID";
    public static final String LINKID_PK_COLUMN = "LINKID";

    public void setRef(String ref) {
        writeProperty("ref", ref);
    }
    public String getRef() {
        return (String)readProperty("ref");
    }

}
