package test.auto;

import test.BaseEntity;

/**
 * Class _Instr was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Instr extends BaseEntity {

    public static final String INSTR_ATTRIBUTE_PROPERTY = "instrAttribute";

    public static final String ID_PK_COLUMN = "ID";
    public static final String LINKID_PK_COLUMN = "LINKID";

    public void setInstrAttribute(String instrAttribute) {
        writeProperty("instrAttribute", instrAttribute);
    }
    public String getInstrAttribute() {
        return (String)readProperty("instrAttribute");
    }

}
