package test.auto;

import test.BaseEntity;

/**
 * Class _Trade was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Trade extends BaseEntity {

    public static final String TRADE_ATTRIBUTE_PROPERTY = "tradeAttribute";

    public static final String ID_PK_COLUMN = "ID";
    public static final String LINKID_PK_COLUMN = "LINKID";

    public void setTradeAttribute(String tradeAttribute) {
        writeProperty("tradeAttribute", tradeAttribute);
    }
    public String getTradeAttribute() {
        return (String)readProperty("tradeAttribute");
    }

}
