
# Allow to build PDF and PS version of the User's and Developer's Guides

# Warning, this Makefile will run by default only when it is called
# with Ant (see the hard-coded paths in rules.mk)

all:
	cd userGuide; make all

clean: 
	cd userGuide; make clean
