package test.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import test.cayenne.T2;

/**
 * Class _T1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _T1 extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String T2S_PROPERTY = "t2s";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToT2s(T2 obj) {
        addToManyTarget("t2s", obj, true);
    }
    public void removeFromT2s(T2 obj) {
        removeToManyTarget("t2s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<T2> getT2s() {
        return (List<T2>)readProperty("t2s");
    }


}
