package test.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;

import test.cayenne.T1;

/**
 * Class _T2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _T2 extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String T1_PROPERTY = "t1";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setT1(T1 t1) {
        setToOneTarget("t1", t1, true);
    }

    public T1 getT1() {
        return (T1)readProperty("t1");
    }


}
