CREATE TABLE COMPIERE.AD_FOREIGNKEYINFO  (
		  CONSTRAINTNAME VARCHAR(126) NOT NULL , 
		  TABLENAME VARCHAR(62) NOT NULL , 
		  P_TABLENAME VARCHAR(62) , 
		  C_TYPE CHAR(1) DEFAULT 'F'  NOT NULL, 
		  C_STATEMENT VARCHAR(2000) , 
		  ORIGINALNAME VARCHAR(128) )  ;

COMMENT ON COLUMN COMPIERE.AD_FOREIGNKEYINFO.C_TYPE IS 'F: FK, P:PK, T:Trigger';


ALTER TABLE COMPIERE.AD_FOREIGNKEYINFO 
	ADD CONSTRAINT AD_FOREIGNKEYINFO_KEY PRIMARY KEY
		(CONSTRAINTNAME);

